kits:
- ==: xt449.gungamekits.MainConfiguration$KitData
  rank: 1
  helmet: DIAMOND_HELMET 1 GENERIC_ARMOR:5
  chestplate: DIAMOND_CHESTPLATE 1 GENERIC_ARMOR:5
  leggings: DIAMOND_LEGGINGS 1 GENERIC_ARMOR:5
  boots: DIAMOND_BOOTS 1 GENERIC_ARMOR:5
  items:
  - DIAMOND_SWORD 1 GENERIC_ATTACK_DAMAGE:10 GENERIC_ATTACK_SPEED:5
