# @author xt449
# Copyright BinaryBanana/xt449 2019
# All Rights Reserved

main: ${project.groupId}.${project.artifactId}.${project.name}
name: ${project.name}
version: ${project.version}
author: xt449
api-version: '1.14'